### ISSUE TITLE
Viewer页面下载图标无法点击

### ISSUE THREAD

**Issue by Cloudac7** [CircleLiu/Comic-Fuz-Downloader#1]
如下图所示，Download图标出现在页面底部，但无法点击下载：
![image](https://user-images.githubusercontent.com/13016685/142629263-7505d13e-f18b-46b6-99bb-2e082e2cd200.png)
F12显示，该处div内部只有两个img元素和一个span元素，点击行为无效。
![image](https://user-images.githubusercontent.com/13016685/142629435-726bc162-9b6f-43dc-8ce8-6ab36b360a94.png)
经查应该是div元素范围较小且无点击反馈，无法直观看到下载判定区域。

**Comment by CircleLiu** [comment]
- 经过测试Edge浏览器确实会有因为fetch api缓存机制与chrome浏览器不同导致的无法拿到图片信息请求数据的bug。Edge的fetch在有缓存的情况下似乎会直接拿到数据而没有实际调用window.fetch，这导致插件无法截获请求信息。我暂时还没有查到相关问题的说明。暂时的解决办法是清除浏览器缓存或在DevTools的Network中勾选Disable Cache再重新加载页面。
- 对于div范围已经更新了鼠标指针来指示点击范围。并更新了下载不成功时的错误提示。

**Comment by Cloudac7** [comment]
> * 经过测试Edge浏览器确实会有因为fetch api缓存机制与chrome浏览器不同导致的无法拿到图片信息请求数据的bug。Edge的fetch在有缓存的情况下似乎会直接拿到数据而没有实际调用window.fetch，这导致插件无法截获请求信息。我暂时还没有查到相关问题的说明。暂时的解决办法是清除浏览器缓存或在DevTools的Network中勾选Disable Cache再重新加载页面。
> * 对于div范围已经更新了鼠标指针来指示点击范围。并更新了下载不成功时的错误提示。

谢谢，虽然前者的情况我这边暂时没有遇到，但确实是一个相关的issue。后者修复的话应该可以正常下载。

**Comment by Cloudac7** [comment]
更新，macOS版Edge会有问题
