### ISSUE TITLE
关于显示页数与实际页数不匹配

### ISSUE THREAD

**Issue by ann840925** [CircleLiu/Comic-Fuz-Downloader#3]
您好 想请问下
今日有本新杂志官方总页数设定错误
(就是比如只有200页
但总页数却弄成了400页)
导致后面因为没有图片而读取不到所以无法下载
不知晚点官方是否会修正
顺便想问问下载时有没有办法设定想下载的页数

**Comment by CircleLiu** [comment]
今天的Carat页数不匹配问题正在修复，抱歉造成不便。
自定义下载页数的功能可以考虑添加。

**Comment by CircleLiu** [comment]
针对无法下载的问题的更新已发布

**Comment by ann840925** [comment]
> 针对无法下载的问题的更新已发布

辛苦了，谢谢
