### ISSUE TITLE
关于下载时failed to get data

### ISSUE THREAD

**Issue by LeavingLeaves** [CircleLiu/Comic-Fuz-Downloader#4]
在试了很多次发现，一个页面好像只能下载一次？
下了一次之后再怎么刷新点下载都会fail
但如果把页面关了再重新打开又可以正常下载
用的是chrome浏览器

**Comment by LeavingLeaves** [comment]
更具体一点的话，好像是只要切到了另一话，就必须重新打开页面才能下载？

**Comment by CircleLiu** [comment]
收到，会尽快确定问题的

**Comment by CircleLiu** [comment]
新版本已发布
