### ISSUE TITLE
官方似乎更新了網頁

### ISSUE THREAD

**Issue by ann840925** [CircleLiu/Comic-Fuz-Downloader#7]
目前點擊下載
會出現這些文字而無法下載
![QQ截图20230215233554](https://user-images.githubusercontent.com/48669994/219075354-65dbde76-0e68-4dd6-85f1-54bf2e3a14bc.png)
再麻煩C大看看了

**Comment by CircleLiu** [comment]
已经发布修复的版本，请更新一下再试试还有没有问题
非常抱歉造成不便

**Comment by ann840925** [comment]
沒事沒事，感謝一直的更新維護
剛剛更新試了下還是一樣的情況
有試過重新安裝了
再麻煩看看

**Comment by CircleLiu** [comment]
请问是哪部漫画的哪个章节？

**Comment by ann840925** [comment]
https://comic-fuz.com/manga/3140
Episode.10

**Comment by CircleLiu** [comment]
又更新了一版`0.4.8`，测试了一下应该OK了，麻烦再试试还有没有问题

**Comment by ann840925** [comment]
可以了，非常感謝！
