### ISSUE TITLE
get apt not defined

### ISSUE THREAD

**Issue by DungbigD** [CircleLiu/Comic-Fuz-Downloader#8]
![image](https://user-images.githubusercontent.com/98143937/233424256-b4c96dfa-1851-476f-8db0-e4e7597099c3.png)

**Comment by CircleLiu** [comment]
This function is in the dependency declared in line 26.

**Comment by DungbigD** [comment]
![image](https://user-images.githubusercontent.com/98143937/233425911-06cef8cb-bd6c-47fb-8e85-ec354853e181.png)
but i don't see the download button. Maybe I use it in wrong way?

**Comment by CircleLiu** [comment]
![image](https://user-images.githubusercontent.com/34266654/233427038-c17be905-e6db-4da1-b071-6a89d536aef8.png)
Check if there is a red icon on the tampermonkey indicating this script is working. Try to refresh the page.
If still not working, could you provide the link of that comic and maybe I can have a check.

**Comment by DungbigD** [comment]
![image](https://user-images.githubusercontent.com/98143937/233433160-b3bd1b3b-59bf-4d9f-9a28-134d18552b5a.png)
I don't see the red icon 
And here is the link of the manga I'm trying to download: https://comic-fuz.com/manga/218

**Comment by DungbigD** [comment]
ohhh I thinks my browser cause the code not working, I just change from chrome to opera recently, after roll back to chrome it work. Sorry for bother you at this time
