### ISSUE TITLE
下載時Loading卡在某一頁

### ISSUE THREAD

**Issue by ann840925** [CircleLiu/Comic-Fuz-Downloader#9]
您好 不好意思
最近下載２０２３年８月号 まんがタイムきららフォワード時發現
Loading會一直卡在後面某頁(重新整理後有時候是卡在452)
嘗試把總頁數改成452的話 會變成卡在448之類的
如圖
![L](https://github.com/CircleLiu/Comic-Fuz-Downloader/assets/48669994/51e97136-35f2-4747-8b5b-3d9e24c42b1e)
能麻煩看看嗎?

**Comment by CircleLiu** [comment]
抱歉无法复现问题，询问了其他用户推测可能是网络原因。

尝试更新了一个版本0.4.9，加入了timeout和retry机制，并且在图片请求之间加入了delay避免同时大量发送请求。
请尝试是否有解决问题。

如果仍有问题可以reopen这个issue

**Comment by ann840925** [comment]
今天很順利載成功了
不過昨天其實前面也很流暢，就是最後幾頁才會卡住而已
不知道什麼原因
總之麻煩您了，謝謝！
